### ISSUE TITLE
Authentication error: code 400 (API_ID_PUBLISHED_FLOOD)

### ISSUE THREAD

**Issue by ildar** [ars3niy/tdlib-purple#95] opened 2020-11-19 06:02 UTC
yesterday the plugin stopped working. Timeline:
1. it crashed
2. restart & connect failed with `Wrong version 26` (*)
3. removing `tdlib` folder fails with API_ID_PUBLISHED_FLOOD (**)

```
(*) [ 0][t 4][1605725049.798683167][LogEvent.h:212][#1][!NetStatsManager][&version()
 < static_cast<int32>(Version::Next)]   Wrong version 26
```
```
(**) (00:49:30) connection: Connection error on 0x27bg360 (reason: 0 description: Authentication error: code 400 (API_ID_PUBLISHED_FLOOD))
```
I suspect fixing https://github.com/ars3niy/tdlib-purple/blob/master/CMakeLists.txt#L10 might help...

**Comment by ars3niy** [comment] 2020-11-19 16:53
So, those chickens finally came home to roost.

This should be fixed by passing `-DSTUFF=AFADBDIyvuCrHF@E@GCC@qAvGus@rIArrGGtIvqC` when running cmake. Talking about what it means is technically a violation of Telegram's terms of service.

**Comment by ildar** [comment] 2020-11-19 16:59
Would rasing tdlib version help?

**Comment by ars3niy** [comment] 2020-11-19 17:08
At this point, no. The "Wrong version" message is normally caused by trying to downgrade tdlib, and fixed by removing tdlib data which you did. At that point it's no longer a tdlib issue.

**Comment by ildar** [comment] 2020-11-25 09:25
Привет, Арсений!
Thank you. That helped.
I am going to build and pack this fixed version to ALTLinux, see
https://packages.altlinux.org/ru/sisyphus/srpms/tdlib-purple.
Do you mind? If you want, please write privately.
P.S. Is there a chat or well-known place to discuss tdlib-purple ?

**Comment by iamleot** [comment] 2020-11-25 09:45
Hello @ildar!
Yes, there is a [Telegram group](https://t.me/joinchat/BuRiSBO0mMw7Lxy0ufVO5g) to discuss about [tdlib-purple](https://github.com/ars3niy/tdlib-purple).

**Comment by ars3niy** [comment] 2020-11-25 12:05
Yes, it's similar to what I'm doing already with the binary packages I'm building.

You can have a look at my RPM spec for inspiration https://build.opensuse.org/package/show/home:ars3n1y/tdlib-purple

**Closed** 2020-11-26 06:08 UTC
