### ISSUE TITLE
Add an option to disable the sending of read receips

### ISSUE THREAD

**Issue by Grarie** [ars3niy/tdlib-purple#99] opened 2020-12-15 18:53 UTC
If I open a chat which contains new messages, all those messages get market as "read" on all my devices.
Sometimes (most often) I don't want that to happen. I want to use my mobile as master device and since it's not possible to mark something as unread in pidgin, as it's possible in the official client, it would be nice, if I could disable the feature of sending receipts globally.

It could be done as in telegram-purple which has a check-box in the plugin-options.

**Comment by BenWiederhake** [comment] 2020-12-15 19:05
https://github.com/ars3niy/tdlib-purple/milestone/1

**Comment by vitalyster** [comment] 2020-12-15 19:23
Duplicate of #22?

**Comment by ars3niy** [comment] 2020-12-31 16:27
Such option would be an explicit terms of service violation. I've still added one that will be only active under bitlbee and spectrum but for pidgin, I'll do in one of the ways outlined in https://github.com/ars3niy/tdlib-purple/issues/22 .

**Closed by ars3niy** 2020-12-31 16:27 UTC
